dataset:
  batch_size: 32
  cleaned: false
  module: datasets.tu
  root: ./data/ENZYMES
  seed: 2021
  use_node_attr: false
experiment:
  name: nervepool-ENZYMES-2021
logger:
  log_dir: diffpool_2021
  log_interval: 10
  logger_name: csvlogger
  model_str: diffpool
model:
  hidden_channels: 64
  hidden_linear_layer: 64
  in_channels: 3
  max_num_nodes: null
  module: models.nervepool
  normalize: false
  num_classes: 6
  use_linear_layer: false
trainer:
  epochs: 100
  lr: 0.01
