config:
  hidden_channels: 64
  hidden_linear_layer: 64
  in_channels: 5
  max_num_nodes: null
  module: models.nervepool
  normalize: false
  num_classes: 21
  use_linear_layer: false
dataset:
  batch_size: 32
  cleaned: false
  module: datasets.mantra2d
  root: data/mantra2d
  seed: 2024
  use_node_attr: false
experiment:
  name: nervepool-mantra2d-2024
logger:
  log_dir: nervepool
  log_interval: 10
  logger_name: csvlogger
  model_str: nervepool
model:
  hidden_channels: 64
  hidden_linear_layer: 64
  in_channels: 5
  max_num_nodes: null
  module: models.nervepool
  normalize: false
  num_classes: 21
  use_linear_layer: false
trainer:
  epochs: 50
  lr: 0.001
