dataset:
  batch_size: 32
  cleaned: false
  module: datasets.tu
  root: ./data/MUTAG
  seed: 2025
  use_node_attr: false
experiment:
  name: mincut-MUTAG-2025
logger:
  log_dir: mincut_2025
  log_interval: 10
  logger_name: csvlogger
  model_str: mincut
model:
  hidden_channels: 64
  hidden_linear_layer: 64
  in_channels: 7
  max_num_nodes: 150
  mincut_temperature: 2
  module: models.mincut
  normalize: false
  num_classes: 2
  use_linear_layer: false
trainer:
  epochs: 50
  lr: 0.001
