dataset:
  batch_size: 32
  cleaned: false
  module: datasets.tu
  root: ./data/DD
  seed: 2023
  use_node_attr: false
experiment:
  name: scratch-DD-2023
logger:
  log_dir: topk_2023
  log_interval: 10
  logger_name: csvlogger
  model_str: topk
model:
  hidden_channels: 64
  max_num_nodes: 500
  pool_ratio: 0.9
  module: models.nopool
  num_classes: 2
  num_features: 89
  out_channels: 64
trainer:
  epochs: 10
  lr: 0.001
