dataset:
  batch_size: 32
  cleaned: false
  module: datasets.tu
  root: ./data/MUTAG
  seed: 2020
  use_node_attr: True
experiment:
  name: nervepool-MUTAG-2020
logger:
  log_dir: nervepool_2020
  log_interval: 10
  logger_name: csvlogger
  model_str: nervepool
model:
  max_num_nodes: 500
  module: models.nervepool
  num_hidden_channels: 64
  num_classes: 2
  num_nodes: 16
  num_features: 7
  normalize: True
  use_linear_layer: False
trainer:
  epochs: 50
  lr: 0.001
