dataset: 
  module: datasets.tu
  root: 
    - ./data/DD
    - ./data/MUTAG
    - ./data/PROTEINS
    - ./data/ENZYMES
  seed: 
    - 2025
    - 2024
    - 2023
    - 2022 
    - 2021
    - 2020
  batch_size: 32
  use_node_attr: False
  cleaned: False

model: 
  module: models.mincut
  hidden_channels: 64
  hidden_linear_layer: 64
  use_linear_layer: False
  mincut_temperature: 2
  normalize: False

logger: 
  log_dir: mincut
  model_str: mincut
  log_interval: 10
  logger_name: csvlogger

trainer:
  epochs: 50
  lr: 0.001
