dataset:
  batch_size: 32
  cleaned: false
  module: datasets.tu
  root: ./data/ENZYMES
  seed: 2024
  use_node_attr: false
experiment:
  name: sagpool-ENZYMES-2024
logger:
  log_dir: sagpool_2024
  log_interval: 10
  logger_name: csvlogger
  model_str: sagpool
model:
  hidden_channels: 64
  hidden_linear_layer: 64
  in_channels: 3
  max_num_nodes: null
  module: models.sagpool
  num_classes: 6
  pool_ratio: 0.9
trainer:
  epochs: 50
  lr: 0.001
