dataset:
  batch_size: 32
  cleaned: false
  module: datasets.tu
  root: ./data/MUTAG
  seed: 2024
  use_node_attr: false
experiment:
  name: nopool-MUTAG-2024
logger:
  log_dir: nopool_2024
  log_interval: 10
  logger_name: csvlogger
  model_str: nopool
model:
  hidden_channels: 64
  hidden_linear_layer: 64
  in_channels: 7
  max_num_nodes: 150
  module: models.nopool
  num_classes: 2
trainer:
  epochs: 50
  lr: 0.001
