dataset:
  batch_size: 32
  cleaned: false
  module: datasets.tu
  root: ./data/MUTAG
  seed: 2020
  use_node_attr: false
experiment:
  name: topk-MUTAG-2020
logger:
  log_dir: topk_2020
  log_interval: 10
  logger_name: csvlogger
  model_str: topk
model:
  hidden_channels: 64
  hidden_linear_layer: 64
  in_channels: 7
  max_num_nodes: 150
  module: models.topk
  num_classes: 2
  pool_ratio: 0.9
trainer:
  epochs: 50
  lr: 0.001
